# Generated by Django 3.1 on 2020-08-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('message', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('1', 'High'), ('2', 'Medium'), ('3', 'Low'), ('4', 'Very Low')], default='1', max_length=1)),
            ],
            options={
                'ordering': ['status'],
            },
        ),
    ]
